apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
    name: message-to-service-b
spec:
    topic: message-to-service-b
    routes:
        default: /api/data
    pubsubname: pubsub
scopes:
    - service-b
    - service-c
